target: solver61 solver43 solver43-2

solver61 : solver61.c puzzlelib.c hex61.c
	cc -O3 -o solver61 solver61.c

solver43 : solver43.c puzzlelib.c hex43.c
	cc -O3 -o solver43 solver43.c

solver43-2 : solver43-2.c puzzlelib.c hex43-2.c
	cc -O3 -o solver43-2 solver43-2.c
